### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by apoorv-on-git** [virtual-tech-school/youtube-clone#1]
Create Navbar similar to YouTube with similar things - 

- [x] Sidebar Toggle Button & Logo (Left)
- [x] Search Bar (Centre)
- [x] User Buttons (Right Side)

Reference - https://www.youtube.com/

Branch Name = issue-1

**Comment by prajapatiomkar** [comment]
Amazing Apoorv, I fork it and setup done it time to build.
