### ISSUE TITLE
doc: add issue template 

### ISSUE THREAD

**Issue by SuperAayush** [virtual-tech-school/youtube-clone#16]
In order to correctly structure the issue created and make it easy for the maintainer of the repo to look into what the issue is, it is recommended to make an issue template.
Refer to this page for creating issue template: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by aroramrinaal** [comment]
Hey I would like to take up this issue.
