### ISSUE TITLE
Side Bar

### ISSUE THREAD

**Issue by apoorv-on-git** [virtual-tech-school/youtube-clone#2]
Create a Sidebar similar to YouTube with similar things -

- [x] General Section
- [x] History Section
- [x] Subscription Section
- [x] More From YouTube Section
- [x] Settings
- [x] Sidebar Footer

Reference - https://www.youtube.com/

Branch Name = issue-2

**Comment by SaarthakMaini** [comment]
Hi Apoorv,
I would like to work on the issue. May I?
I am at a beginner level so it might take me some time to learn and apply.
Thank you
